### ISSUE TITLE
Elevator interpolating pressure to pressure levels is not constant

### ISSUE THREAD

**Issue by olafurrognvaldsson** [Belgingur/WrfUtils#20]
When testing the latest version of WrfUtils I noticed that the pressure variable is neither constant in time nor space when data is being interpolated to constant pressure levels.

![Screen Shot 2019-12-31 at 11 18 14](https://user-images.githubusercontent.com/18738411/72422276-09500b80-377a-11ea-94f8-78a83e5bdb2b.png)

The plot above shows an example of this, top shows a time-series for the geopotential height at 900hPa and the bottom shows a time-series (from the same location) of pressure. The bottom plot should show a flat line (more or less) and the value should be 90000 Pa, and not 900 Pa.

**Comment by logi** [comment]
The easiest part of this is that the unit for `pressure` should be `hPa` and not `Pa`.

**Comment by logi** [comment]
@olafurrognvaldsson how does this look for a pressure lower than 900hPa? Could this be the terrain blowing through the pressure level?

**Comment by olafurrognvaldsson** [comment]
@logi what should I be looking at :)

**Comment by logi** [comment]
Click the `bottom_top` value in `ncview` and it'll show a different vertical level.

Meanwhile I've realised that I was testing this with a tiny file and might not have any visible variability in it so I'm re-running with a 1.4GB africa-50 file.

**Comment by logi** [comment]
This is what I see at the 500hPa level, so it looks pretty constant except that it's constant at 514.3 - 514.4 hPa instead of 500 hPa.

![mynd](https://user-images.githubusercontent.com/217723/72443150-1d156500-37ae-11ea-9742-79fff515260d.png)
![mynd](https://user-images.githubusercontent.com/217723/72443166-26063680-37ae-11ea-92b2-295f45dc1528.png)
![mynd](https://user-images.githubusercontent.com/217723/72443190-2f8f9e80-37ae-11ea-977c-cea34d50ac08.png)

**Comment by olafurrognvaldsson** [comment]
Does the geoponential_height have the same shape in this particular point (like it did for my test case)?

**Comment by logi** [comment]
Geopotential height in 500hPa
![mynd](https://user-images.githubusercontent.com/217723/72443731-0ae7f680-37af-11ea-98b7-c6037e758b45.png)

Geopotential height in 750hPa. You can see the highest mountains as a few individual pixels (disabling interpolation in image)
![mynd](https://user-images.githubusercontent.com/217723/72443897-5ac6bd80-37af-11ea-9e50-cb58db280e89.png)

Geopotential height in 900hPa. A lot of the continent sticks out
![mynd](https://user-images.githubusercontent.com/217723/72444007-92356a00-37af-11ea-8a8f-765171601499.png)

**Comment by olafurrognvaldsson** [comment]
No I meant how does the time-series for geopotential_height for point (3, 145, 43) look like?

**Comment by logi** [comment]
Ranges from 5620m to 5645m
![mynd](https://user-images.githubusercontent.com/217723/72444624-a4fc6e80-37b0-11ea-88a6-18e408d56573.png)

**Comment by olafurrognvaldsson** [comment]
Can you re-run the elevator script and add variables `P` and `PB` to the output file and make it available somewhere so that I can open it?

**Comment by logi** [comment]
`sleggjan:~logi/wrfout-africa-pressure.nc4` should be ready in 10 seconds

**Comment by olafurrognvaldsson** [comment]
Stuck in a skype-meeting. Will take a look in 20-30 min

**Comment by logi** [comment]
The interpolation of `geopotential_height` to height above sea-level is very precisely constant and I would expect the `pressure` variable to be about as constant when interpolated to pressure levels. I'm going to read through some code to see if it makes any sense.

**Comment by logi** [comment]
OK, I've found a bug. The interpolation constants for vertically staggered or unstaggered variables are created for pressure levels from `(P+PB)/100` like for `(PH+PHB)/g` but the latter is vertically staggered while the former is not, so the interpolation is slightly wrong which would explan the `514hPa` issue. The 14hPa is presumably half a sigma level.

**Comment by logi** [comment]
With that fix (not committed)
![mynd](https://user-images.githubusercontent.com/217723/72447966-8c8f5280-37b6-11ea-94ff-5aef45dcd91d.png)

**Comment by logi** [comment]
@olafurrognvaldsson I believe this task is done and have moved it to the Done column. If you try "your thing" again and it looks correct, please close the issue.

**Comment by olafurrognvaldsson** [comment]
@logi should I update my WrfUtils repo? I.e. has the fix been committed ?

**Comment by logi** [comment]
Yup. You can also see the commit just above here as
`downloader@binary.belgingur.is:wod_test_data/jobs/2016/10/20161024-africa-50/model/wrfout_d01_2016-10-24_06:00:00`

**Comment by olafurrognvaldsson** [comment]
Looking good, case closed !!
