### ISSUE TITLE
Variable "Time" is not "unlimited" when written to file via DropDigits

### ISSUE THREAD

**Issue by olafurrognvaldsson** [Belgingur/WrfUtils#22]
DropDigits does not label the time-variable as `unlimited` when writing it to a new file

**Comment by logi** [comment]
IIRC this allows the files to be compressed more aggressively and the idea was that the dataset was already compete. What is the problem being caused by this?

**Comment by olafurrognvaldsson** [comment]
The files can not be read by the LVC code. I think this Stackoverflow issue is relevant - https://stackoverflow.com/questions/20340977/using-mfdataset-to-combine-netcdf-files-in-python

**Comment by olafurrognvaldsson** [comment]
@kstanislawska could you give a more accurate description?

**Comment by logi** [comment]
The MFDataset can only read a collection of files if their time dimension is unlimited. And I suppose it is out of the question to combine them into a single file.

**Comment by olafurrognvaldsson** [comment]
yes, a typical size for a one-year batch is ~350GB
