### ISSUE TITLE
DropDigits: Temperature incorrectly calculated in `calculators.py`

### ISSUE THREAD

**Issue by olafurrognvaldsson** [Belgingur/WrfUtils#23]
There is a minor bug in `calculators.py ` resulting from the updated definition of `pressure`
```
@derived(
    units='hPa',
    datatype=np.int16,
    add_offset=655.36,
    scale_factor=0.02,  # 0..
)
def pressure(P, PB):
    return (P + PB) / 100
```
As pressure in now defined in hPa, and not Pa, we need to update the computation of `temperature` accordingly (which expects `pressure` to be in Pa, and not hPa).
We need to change this
```
def temperature(potential_temperature, pressure):
    return potential_temperature * (pressure / 100000.0) ** 0.2856
```
to this
```
def temperature(potential_temperature, pressure):
    return potential_temperature * (pressure / 1000.0) ** 0.2856
```

**Comment by olafurrognvaldsson** [comment]
Please note that this bug is not linked to the erroneous behavior of `Elevator.py`with regards to the `PB` variable.

**Comment by logi** [comment]
@olafurrognvaldsson I'm adding this to the `lv-2020-azure` project so it gets attention. See the Project box in the right side-bar.

**Comment by logi** [comment]
Oh, I didn't realise that you'd actually identified the exact issue or I'd have just made and committed that change yesterday.

**Comment by logi** [comment]
After some consultations we're returning `pressure` to being in Pa rather than hPa and then the temperature calculator will be correct again.

**Comment by logi** [comment]
@olafurrognvaldsson is temperature looking correct now then?

**Comment by olafurrognvaldsson** [comment]
Yes, for the "old" versions of RÁV2 output files. We still have problems with the 2018-19 data

**Comment by logi** [comment]
Is Temperature being calculated incorrectly for the 2018-2019 data? Is that the same data as in #25?

**Comment by olafurrognvaldsson** [comment]
This particular issue can be closed. The reason `temperature` is incorrect in the 2018-19 data is that the code is not interpreting the input variable `PB` correctly. Hence the value of `pressure` becomes incorrect which in turn leads to incorrect values of `temperature`. The equation for calculating `temperature` has been corrected (this issue), it's just the input to said equation that is wrong (issue #25)
