### ISSUE TITLE
Wiski: library dependency issues

### ISSUE THREAD

**Issue by logi** [Belgingur/WrfUtils#26]
From @olafurrognvaldsson:

I've just built the Wiski environment in conda, but when I run the code I get an error message about a missing module
```
(Wiski) [or@sleggjan Wiski]$ ./accumulation.py -c wiski_lvc.yml -s wrf-ec-03-rav1
Traceback (most recent call last):
  File "./accumulation.py", line 23, in <module>
    from pytz import UTC
ModuleNotFoundError: No module named 'pytz'
(Wiski) [or@sleggjan Wiski]$
```
Is perhaps sth. missing from the `environment.yml` file?

**Comment by logi** [comment]
It probably used to be a dependency of one of our other dependencies and now needs to be declared explicitly

**Comment by logi** [comment]
@olafurrognvaldsson update,  `conda env update` and rerun? 

I don't have data to test this localy, so please close the issue if it runs

**Comment by olafurrognvaldsson** [comment]
@logi
I've updated the repo and updated the `wiski env` as suggested above. Now I get this error: 
```
(Wiski) [or@sleggjan Wiski]$ ./accumulation.py -c wiski_lvc.yml -s wrf-ec-03-rav1
Traceback (most recent call last):
  File "./accumulation.py", line 25, in <module>
    from make_masks import ConfigGetter, read_domain_shape
  File "/sleggjan/home/or/Belgingur-Utils/WrfUtils/Wiski/make_masks.py", line 23, in <module>
    import ogr
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/site-packages/ogr.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/site-packages/osgeo/__init__.py", line 26, in <module>
    _gdal = swig_import_helper()
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/site-packages/osgeo/__init__.py", line 22, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libkea.so.1.4.7: cannot open shared object file: No such file or directory
(Wiski) [or@sleggjan Wiski]$ 
```

**Comment by logi** [comment]
Carp. OK, can you point me to input data I can use for testing?

**Comment by logi** [comment]
We should look into some way to "lock" library versions to those that have been tested and only update to newer as an explicit action that can then be tested. Then we would avoid these kinds of problems.

**Comment by olafurrognvaldsson** [comment]
The `yml` file can be found on `sleggjan:/home/or/Belgingur-Utils/WrfUtils/Wiski/wiski_lvc.yml` and examples of e.g. the RÁV1 dataset can be found here
```
sleggjan:/sleggjan/shared/wrf/V3.0.1-2eq/run/wrfout_d02_*_reducedZ2D.nc4
```

**Comment by olafurrognvaldsson** [comment]
I'm not sure if it is related, but my conda env is not the latest one
```
==> WARNING: A newer version of conda exists. <==
  current version: 4.7.5
  latest version: 4.8.2

Please update conda by running

    $ conda update -n base conda
```
and, annoyingly, there is some bug up the conda but so I can not update to the latest version :(

**Comment by logi** [comment]
Hah, no, you have a pretty recent one from a few days ago and it _should_ not cause this kind of issue anyway. This is some library that has been updated upstream and has unstated dependencies. Those are _enormously_ annoying.

**Comment by olafurrognvaldsson** [comment]
Should I try and use an older version of the wiski-code?

**Comment by logi** [comment]
No, this is not our change but a change to the libraries upstream. This code hasn't been changed for months.

**Comment by logi** [comment]
We declare a dependency on e.g. `shapely=1.6.*` so that they can make a bugfix release from 1.6.2 to 1.6.3 and we get it automatically. But then they change one of their dependencies and the change trickles down to us.

Even if we don't change our dependency at all and hard code `shapely=1.6.3` then they might depend on `geosomething=2.3.*` and when we re-create the conda environment _that_ library gets updated and things change for us.

The way around this is to "frieze" dependencies where we start with our `environment.yml` file and use that to resolve all the transitive dependencies at some particular time and write the result to a file. Then everyone uses that frozen file to create the environment. If we then want to change or update our dependencies we update the `environment.yml` file (or not, if we just want some bugfix updates) and re-resolve and re-create the frozen file and test that everything works before pushing the changed frieze file (and perhaps `environment.yml` file) to git so that everyone who pulls it gets a known-good version.

I haven't spend the time to sort out exactly how to do that, but if I had, then we wouldn't be having this issue or this discussion now.

**Comment by logi** [comment]
Works for me with a fresh Wiski environment and the first 3 `wrf-ec-03-rav1` files:
![Langjökull_wrf-ec-03-rav1_accumulation](https://user-images.githubusercontent.com/217723/73352871-5d86df80-4292-11ea-8b5b-24c4370921a6.png)

Try running:
```
conda deactivate
conda env remove Wiski
conda env create
conda env activate Wiski
```
and then trying again.

**Comment by olafurrognvaldsson** [comment]
```
(Wiski) [or@sleggjan Wiski]$ ./accumulation.py -c wiski_lvc.yml -s wrf-ec-03-rav1
Traceback (most recent call last):
  File "./accumulation.py", line 25, in <module>
    from make_masks import ConfigGetter, read_domain_shape
  File "/sleggjan/home/or/Belgingur-Utils/WrfUtils/Wiski/make_masks.py", line 23, in <module>
    import ogr
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/site-packages/ogr.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/site-packages/osgeo/__init__.py", line 26, in <module>
    _gdal = swig_import_helper()
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/site-packages/osgeo/__init__.py", line 22, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libkea.so.1.4.7: cannot open shared object file: No such file or directory
(Wiski) [or@sleggjan Wiski]$ 
```
and this is after having removed and rebuilt the `Wiski` env from scratch :(

**Comment by olafurrognvaldsson** [comment]
What conda version do you have?

**Comment by logi** [comment]
```
(Wiski) logi@saxi:~/belgingur.is/WrfUtils.git/Wiski$ conda --version
conda 4.8.1
```
But the libraries are supposed to have their own versions independent of the version of the conda command or the default installed libraries.

**Comment by olafurrognvaldsson** [comment]
Strange, the code is complaining about not finding 
```
ImportError: libkea.so.1.4.7: cannot open shared object file: No such file or directory
```
and that is true, the recently created `Wiski` env has a more recent version of this lib
```
(base) [or@sleggjan Wiski]$ pwd
/home/or/miniconda3/envs/Wiski
(base) [or@sleggjan Wiski]$ find . -iname libkea.so"*"
./lib/libkea.so
./lib/libkea.so.1.4
./lib/libkea.so.1.4.10
(base) [or@sleggjan Wiski]$
```
Can you see what version you have?

**Comment by logi** [comment]
```
(Wiski) logi@saxi:~/belgingur.is/WrfUtils.git/Wiski$ ll ~/conda/envs/Wiski/lib/libkea*
lrwxrwxrwx 1 logi logi   15 jan 29 11:16 /home/logi/conda/envs/Wiski/lib/libkea.so -> libkea.so.1.4.7
lrwxrwxrwx 1 logi logi   15 jan 29 11:16 /home/logi/conda/envs/Wiski/lib/libkea.so.1.4.6 -> libkea.so.1.4.7
-rwxrwxr-x 2 logi logi 470K maí 11  2018 /home/logi/conda/envs/Wiski/lib/libkea.so.1.4.7
```
It is an ugly hack, but if you symlink libkea.so.1.4.7 to libkea.so.1.4.10 then it should work

It might also work to nuke your entire conda library and set up from scratch, but that's a bit drastic

**Comment by olafurrognvaldsson** [comment]
I've already tried linking libkea.so.1.4.7 to libkea.so.1.4.10, but that just gives me another error
```
(Wiski) [or@sleggjan Wiski]$ ./accumulation.py -c wiski_lvc.yml -s wrf-ec-03-rav1
Traceback (most recent call last):
  File "./accumulation.py", line 25, in <module>
    from make_masks import ConfigGetter, read_domain_shape
  File "/sleggjan/home/or/Belgingur-Utils/WrfUtils/Wiski/make_masks.py", line 23, in <module>
    import ogr
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/site-packages/ogr.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/site-packages/osgeo/__init__.py", line 26, in <module>
    _gdal = swig_import_helper()
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/site-packages/osgeo/__init__.py", line 22, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/or/miniconda3/envs/Wiski/lib/python3.7/site-packages/osgeo/../../../libgdal.so.20: undefined symbol: _ZNK6libdap5Error17get_error_messageB5cxx11Ev
(Wiski) [or@sleggjan Wiski]$
```

**Comment by olafurrognvaldsson** [comment]
As a last try, before nuking miniconda3, could you send me your version of the `libkea.so.1.4.7` library?

**Comment by logi** [comment]
I have one here:
```
(base) [logi@sleggjan Wiski]$ ll /home/logi/conda/envs/Wiski/lib/libkea.*
lrwxrwxrwx 1 logi logi   15 mar 22  2019 /home/logi/conda/envs/Wiski/lib/libkea.so -> libkea.so.1.4.7
lrwxrwxrwx 1 logi logi   15 mar 22  2019 /home/logi/conda/envs/Wiski/lib/libkea.so.1.4.6 -> libkea.so.1.4.7
-rwxrwxr-x 2 logi logi 470K maí 11  2018 /home/logi/conda/envs/Wiski/lib/libkea.so.1.4.7
```

**Comment by olafurrognvaldsson** [comment]
Now I just get sth. new
```
(Wiski) [or@sleggjan Wiski]$ ./accumulation.py -c wiski_lvc.yml -s wrf-ec-03-rav1
Traceback (most recent call last):
  File "./accumulation.py", line 25, in <module>
    from make_masks import ConfigGetter, read_domain_shape
  File "/sleggjan/home/or/Belgingur-Utils/WrfUtils/Wiski/make_masks.py", line 23, in <module>
    import ogr
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/site-packages/ogr.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/site-packages/osgeo/__init__.py", line 26, in <module>
    _gdal = swig_import_helper()
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/site-packages/osgeo/__init__.py", line 22, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/or/miniconda3/envs/Wiski/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libhdf5_cpp.so.102: cannot open shared object file: No such file or directory
(Wiski) [or@sleggjan Wiski]$ 
```
We could be all day/week tracing this crap so I guess nuking it is

**Comment by logi** [comment]
I have run both `make_masks.py` and a 15-day `accumulation` using that conda environment on `sleggjan`

(with some slight updates to the code which includes your `wisky_lvc.yml` file with explicitly no spinup.)

**Comment by logi** [comment]
If all else fails you can `sudo su - logi`, go to `~WrfUtils/Wiski` and crunch the data there.

**Comment by olafurrognvaldsson** [comment]
@logi what is the syntax for running `make_masks.py`? I get this error
```
usage: make_masks.py [-h] [-v] [-c CONFIG] [-s SIMULATION] [geo]
make_masks.py: error: No configuration found for "simulation" in command-line arguments, "simulation" config or root config
```
when I run it like this `./make_masks.py  /sleggjan/shared/wrf/V3.0.1-2eq/run/GEOfiles/geo_em.d02_reduced.nc4`

**Comment by olafurrognvaldsson** [comment]
Aha, I think I've got it, the `-s` is presumably the name given to the `weights_*.npz` file

**Comment by olafurrognvaldsson** [comment]
hmm, no `./make_masks.py -s wrf-ec-03-rav1  /sleggjan/shared/wrf/V3.0.1-2eq/run/GEOfiles/geo_em.d02_reduced.nc4` results in `weights.npz`.
@logi how did you create `weights_wrf-ec-03-rav1.npz`?

**Comment by logi** [comment]
It's the same as the `accumulate.py` command but without the from/to dates, so `./make_masks.py -c wiski_lvc.yml -s wrf-ec-03-rav1`

**Comment by logi** [comment]
Did this work then?

**Comment by olafurrognvaldsson** [comment]
In the sense I could copy your `Wiski` environment to `/home/or/miniconda3/envs/` and than run it. Nuking miniconda and re-installing/re-creating everything did not solve the dependency issue :(

**Comment by logi** [comment]
Nice :-|

Hopefully this is a temporary upstream issue... I'm closing this one
